# Generated by Django 3.1.12 on 2026-05-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0002_auto_20260527_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyst_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUSPICIOUS', 'Suspicious'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='emissions.emissionrecord')),
            ],
        ),
    ]
